packages:
  - "apps/*"
  - "packages/*"
  - "runtime/*"

catalog: 
  "czg": ^1.10.1
  "cz-git": ^1.10.1
  "sass-migrator": "^2.2.1"
  "@types/node": "20.2.5"
  "@vitest/coverage-v8": "^2.1.8"
  "@vitest/ui": "^2.1.8"
  "lint-staged": "^15.2.10"
  "husky": "^9.1.6"
  "jsdom": "^25.0.1"
  "tslib": "^2.8.1"
  "turbo": "^2.3.3"
  "typescript": "^5.7.2"
  "vite": "^6.0.5"
  "vitest": "^2.1.0"
  "@changesets/cli": "~2.27.7"
  "@commitlint/cli": "^19.5.0"
  "prettier": "^3.4.0"
  "@commitlint/config-conventional": "^19.5.0"
  "commitlint-plugin-function-rules": "^4.0.1"
  "@typescript-eslint/eslint-plugin": "~8.18.2"
  "@typescript-eslint/parser": "~8.18.2"
  "eslint-config-turbo": "~2.3.3"
  "eslint-plugin-vue": "~9.32.0"
  "eslint": "~8.57.0"
  "rollup": "~4.29.1"
  "@rollup/plugin-alias": "~5.1.1"
  "@rollup/plugin-terser": "~0.4.4"
  "@rollup/plugin-typescript": "~12.1.2"
  "@rollup/plugin-commonjs": "~28.0.2"
  "@rollup/plugin-json": "~6.1.0"
  "@rollup/plugin-node-resolve": "~16.0.0"
  "rollup-plugin-external-globals": "^0.6.1"
  "@vitejs/plugin-vue": "~5.2.1"
  "@vitejs/plugin-vue-jsx": "~4.1.1"
  "postcss-pxtorem": "~6.1.0"
  "unplugin-vue-components": "~0.28.0"
  "vite-plugin-compression2": "~1.3.3"
  "vite-plugin-dts": "~4.4.0"
  "vite-plugin-pwa": "~0.21.0"
  "@sentry/vue": "~8.47.0"
  "@sentry/cli": "1.72.0"
  "@sentry/vite-plugin": "~2.22.0"
  "@types/postcss-pxtorem": "~6.0.3"
  "@vue/test-utils": "~2.4.6"
  "sass": "~1.83.0"
  "vue": "~3.5.13"
  "vue-router": "~4.5.0"
  "vue-types": "~5.1.1"
  "pinia": "~2.3.0"
  "sortablejs": "~1.15.0"
  "@types/sortablejs": "~1.15.0"
  "echarts": "~5.4.2"
  "ant-design-vue": "~4.2.6"
  "@ant-design/icons-vue": "~7.0.1"
  "highlight.js": "~11.4.0"
  "vitepress": "1.5.0"
  "less": "~4.2.1"
  "crypto-js": "~4.2.0"
  "@types/crypto-js": "~4.2.0"
  "lodash-es": "~4.17.21"
  "@types/lodash-es": "~4.17.12"
  "qs": "~6.12.2"
  "@types/qs": "~6.9.15"
  "axios": "~1.7.2"
  "dayjs": "~1.11.7"
  "csstype": "~3.1.2"
  "@nuxt/kit": "~3.15.0"
  "magic-string": "~0.30.0"
  "unplugin": "~2.1.0"
  "nuxt": "~3.15.0"
  "@nuxt/module-builder": "~0.8.4"
  "@nuxt/schema": "~3.15.0"
  "monaco-editor": "^0.52.2"
  "tinymce": "^5.10.9"
  "nprogress": "0.2.0"
  "@types/nprogress": "0.2.0"
  "element-resize-detector": "1.2.4"
  "@types/element-resize-detector": "1.1.3"
  "vue-tsc": "1.8.8"
  "workbox-build": "~7.3.0"
  "workbox-window": "~7.3.0"
  "fs-extra": "~11.2.0"
  "@types/fs-extra": "~11.0.4"
  "chalk": "4.1.2"
  "rimraf": "^3.0.2"
  "keycon": "^1.4.0"
  "moveable": "^0.51.1"
  "moveable-helper": "^0.4.0"
  "@vitejs/plugin-vue2": "^2.2.3"
  "@vitejs/plugin-vue2-jsx": "^1.1.1"
  "@quantum-design-configs/vite": "~2.0.2-beta.0"
  "@quantum-design/hooks": "~2.0.2-beta.0"
  "@quantum-design/http": "~2.0.2-beta.0"
  "@quantum-design/shared": "~2.0.2-beta.0"
  "@quantum-design/vue3-antd-pc-ui": "~2.0.3-beta.0"
  "@quantum-design/vue3-pc-ui": "~2.0.2-beta.0"
  "@quantum-design/types": "~2.0.2-beta.0"
  "@quantum-design-configs/rollup": "~2.0.2-beta.0"
  "@quantum-design-configs/eslint": "~2.0.2-beta.0"
  "@quantum-design-configs/tsconfig": "~2.0.2-beta.0"
  "@quantum-design/utils": "~2.0.2-beta.0"
  "@quantum-design/styles": "~2.0.2-beta.0"
