/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    QAntdIcon: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdIcon']
    QAntdKeepAliveTabs: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdKeepAliveTabs']
    QAntdSearch: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdSearch']
    QAntdSetting: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdSetting']
    QBreadcrumb: typeof import('@q-front-npm/vue3-pc-ui/es')['QBreadcrumb']
    QLoading: typeof import('@q-front-npm/vue3-pc-ui/es')['QLoading']
    QmAside: typeof import('./src/components/layout/qm-aside.vue')['default']
    QmAuthority: typeof import('./src/components/qm-authority/index.vue')['default']
    QmHeader: typeof import('./src/components/layout/qm-header.vue')['default']
    QmReloadPrompt: typeof import('./src/components/layout/qm-reload-prompt.vue')['default']
    QThemeModeButton: typeof import('@q-front-npm/vue3-pc-ui/es')['QThemeModeButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
