/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CompList: typeof import('./src/components/classic/sidebar/comp-list/index.vue')['default']
    Preview: typeof import('./src/components/pagePreview/preview.vue')['default']
    PropsList: typeof import('./src/components/classic/sidebar/props-list/index.vue')['default']
    QAntdForm: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdForm']
    QAntdIcon: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdIcon']
    QAntdKeepAliveTabs: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdKeepAliveTabs']
    QAntdSearch: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdSearch']
    QAntdSetting: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdSetting']
    QAntdTable: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdTable']
    QAntdTableAction: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdTableAction']
    QBreadcrumb: typeof import('@quantum-design/vue3-pc-ui/es')['QBreadcrumb']
    QLoading: typeof import('@quantum-design/vue3-pc-ui/es')['QLoading']
    QmAside: typeof import('./src/components/layout/qm-aside.vue')['default']
    QmAuthority: typeof import('./src/components/qm-authority/index.vue')['default']
    QmHeader: typeof import('./src/components/layout/qm-header.vue')['default']
    QmReloadPrompt: typeof import('./src/components/layout/qm-reload-prompt.vue')['default']
    QThemeModeButton: typeof import('@quantum-design/vue3-pc-ui/es')['QThemeModeButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/classic/sidebar/index.vue')['default']
    Src: typeof import('./src/components/json-viewer/src/index.vue')['default']
    ViewModal: typeof import('./src/components/json-viewer/src/view-modal.vue')['default']
  }
}
