/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComponentList: typeof import('./src/components/layouts/sidebar/component-list/index.vue')['default']
    DatasourceFields: typeof import('./src/components/form/datasource-fields.vue')['default']
    DatasourceMethods: typeof import('./src/components/form/datasource-methods.vue')['default']
    EventSelect: typeof import('./src/components/form/event-select.vue')['default']
    Framework: typeof import('./src/components/layouts/framework.vue')['default']
    InputSelect: typeof import('./src/components/form/input-select.vue')['default']
    KeyValue: typeof import('./src/components/form/key-value.vue')['default']
    NavMenu: typeof import('./src/components/layouts/nav-menu.vue')['default']
    PageBar: typeof import('./src/components/layouts/page-bar.vue')['default']
    PropsEditor: typeof import('./src/components/layouts/props-editor.vue')['default']
    QAntdDropdown: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdDropdown']
    QAntdForm: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdForm']
    QAntdIcon: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdIcon']
    QCodeEditor: typeof import('@q-front-npm/vue3-pc-ui/es')['QCodeEditor']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sandbox: typeof import('./src/components/layouts/sandbox.vue')['default']
    Sidebar: typeof import('./src/components/layouts/sidebar/index.vue')['default']
    SplitView: typeof import('./src/components/base/split-view.vue')['default']
    Workspace: typeof import('./src/components/layouts/workspace.vue')['default']
  }
}
