/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Preview: typeof import('./src/components/pagePreview/preview.vue')['default']
    QAntdTable: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdTable']
    QAntdTableAction: typeof import('@q-front-npm/vue3-antd-pc-ui/es')['QAntdTableAction']
    QmAside: typeof import('./src/components/layout/qm-aside.vue')['default']
    QmAuthority: typeof import('./src/components/qm-authority/index.vue')['default']
    QmHeader: typeof import('./src/components/layout/qm-header.vue')['default']
    QmReloadPrompt: typeof import('./src/components/layout/qm-reload-prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/json-viewer/src/index.vue')['default']
    ViewModal: typeof import('./src/components/json-viewer/src/view-modal.vue')['default']
  }
}
